import random


def generate_prompt(member_id):
    prompts = [
        'Hey there, <@{}>! Give us an earworm! :notes:',
        '<@{}> Are you gonna leave us hanging or will you finally tell us your song of the day? :thinking_face:',
        "Alright, <@{}> - spill the tea. What's the song that's been stuck in your head all day? :tea:",
        "Okay, <@{}>. You know the drill. What's the song that's making you feel all the feels? :sparkling_heart:",
        "<@{}> We need your song of the day to keep us going, don't hold out on us! :pray:",
        "Yo, <@{}>! What's the tune that's been rocking your socks off lately? :socks:",
        "<@{}> It's not like we need your song of the day or anything... but we kinda do, so spill the beans! :face_with_hand_over_mouth:",
        "Hey <@{}> - just checking in, have you found a song that's better than yesterday's yet? :eyes:",
        "<@{}> Don't keep us in suspense, what's the song that's been on repeat for you today? :repeat:",
        "Okay <@{}>, it's time to share. What's your song of the day? We won't judge... much. :wink:",
        "Hey <@{}>, have you been listening to anything good today? What's your song of the day? :headphones:",
        'Good morning, <@{}>! Do you have a song of the day to share with us? :sunrise:',
        "Attention all personnel! We need <@{}>'s song of the day to keep us going. What's it gonna be? :loudspeaker:",
        '<@{}>, the world is a dark place without your song of the day. Save us! :world_map:',
        'Rumor has it that <@{}> has the perfect song of the day. Can you confirm or deny? :face_with_monocle:',
        "Hey <@{}>, we heard your music taste is out of this world. What's the song of the day? :alien:",
        '<@{}>, we need your song of the day like a fish needs water. Please quench our thirst! :fish:',
        "Life's too short for bad music. Help us out, <@{}>. What's the song of the day? :clock1:",
        '<@{}>, we need your song of the day to cure our music withdrawal symptoms. Please prescribe it to us! :pill:',
        "Is it too much to ask for <@{}>'s song of the day? Don't keep us waiting! :timer_clock:",
        "Come on, <@{}>. What's the song of the day? Don't be a tease! :stuck_out_tongue_winking_eye:",
        'We know you have good taste in music, <@{}>. Share your song of the day with us! :ok_hand:',
        "Breaking news! <@{}>'s song of the day is now a matter of public interest. Bring it to light immediately! :newspaper:",
        "We interrupt this program to urgently request <@{}>'s song of the day. :rotating_light:",
        '<@{}>, we need your song of the day to keep us from going insane. Help us out! :zany_face:',
        "Okay, <@{}>. We won't judge (much). What's the song that's been stuck in your head all day? :face_with_monocle:",
        'Listen up, <@{}>! We need your song of the day to keep us from falling asleep. Caffeinate us! :coffee:',
        "<@{}>, we're counting on you to save us from the musical abyss with your song of the day. Don't let us down! :musical_note:",
        "We're not saying we need your song of the day to survive, <@{}>. But it would definitely help. :sweat_smile:",
        "<@{}>, we're in a musical emergency. Please send us your song of the day ASAP! :rotating_light:",
        "Good things come to those who share their song of the day, <@{}>. Please don't deprive us of your good taste! :yum:",
        "<@{}>, we're in dire need of your song of the day to keep us from musical bankruptcy. Please bail us out! :money_with_wings:",
        "We're in the middle of a music drought, <@{}>. Share your song of the day to help us weather the storm! :thunder_cloud_and_rain:",
        "Hey <@{}>, we're hanging by a thread here. Share your song of the day with us before it's too late! :sos:",
        "We can't go on without <@{}>'s song of the day. Please share it with us before our musical souls wither away. :dizzy_face:",
        "<@{}>, we're at the mercy of your music taste. What's your song of the day? :pray:",
        'Attention, <@{}>! Your song of the day is crucial to our musical well-being. Share it post-haste! :trumpet:',
        '<@{}>! We need your song of the day like a plant needs sunlight. Enlighten us! :seedling:',
        "Warning! Warning! The lack of <@{}>'s song of the day has reached critical levels. Share it with us to prevent a music disaster. :warning:",
        'No pressure, <@{}>, but the future of all music depends on your song of the day. :robot_face:',
        '<@{}>! We need your song of the day like a fish needs water. Keep us alive! :fish:',
        'The clock is ticking, <@{}>! We need your song of the day to prevent a musical apocalypse. :hourglass_flowing_sand:',
        "Calling all stations! This is an urgent message! We need <@{}>'s song of the day to keep the music flowing. Send it over ASAP! :loudspeaker:",
        "<@{}>! You're our only hope! Please share your song of the day to prevent a musical disaster. :innocent:",
        '<@{}>! We need your song of the day like a bird needs to fly. Help us spread our wings! :bird:',
    ]
    return random.choice(prompts).format(member_id)
